# Generated by Django 4.2.7 on 2025-08-13 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(db_index=True, help_text='Name of the feature', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the feature')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feature is currently available')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'subscription_feature',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(db_index=True, help_text='Name of the subscription plan', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the plan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available for subscription')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the plan (optional)', max_digits=10, null=True)),
                ('features', models.ManyToManyField(blank=True, help_text='Features included in this plan', related_name='plans', to='subscriptions.feature')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'subscription_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='When the subscription started')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the subscription ended (if deactivated)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently active')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this subscription')),
                ('plan', models.ForeignKey(help_text='Plan associated with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(help_text='User who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscription_subscription',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='subscriptio_user_id_123f65_idx'), models.Index(fields=['plan', 'is_active'], name='subscriptio_plan_id_02164f_idx'), models.Index(fields=['start_date'], name='subscriptio_start_d_914d56_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_subscription_per_user'),
        ),
    ]
